version: "3"

services:
  postgres:
    image: postgres:11.5
    environment:
      - POSTGRES_DB=opendatacube
      - POSTGRES_PASSWORD=opendatacubepassword
      - POSTGRES_USER=opendatacube
    restart: always

  index:
    #image: opendatacube/index:latest
    build:
      context: ../../
    environment:
      - WMS_CONFIG_URL=https://raw.githubusercontent.com/GeoscienceAustralia/dea-config/master/dev/services/wms/ows/ows_cfg.py
      - PRODUCT_URLS=https://raw.githubusercontent.com/GeoscienceAustralia/dea-config/master/dev/products/mangrove/product-definition.yaml
      - DC_S3_INDEX_BUCKET=data.deadev.com
      - DC_S3_INDEX_PREFIX=mangrove_cover/-10_-18/
      - DC_S3_INDEX_SUFFIX=.yaml
      - DC_INDEX_PROTOCOL=gs
      - DC_RANGES_PRODUCT=mangrove_cover
      - DB_HOSTNAME=postgres
      - DB_USERNAME=opendatacube
      - DB_PASSWORD=opendatacubepassword
      - DB_DATABASE=opendatacube
      - DB_PORT=5432
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    command:
      - /bin/bash
      - -c
      - "cd index; ./create-index.sh"
